INSERT INTO dominio.pais (idpais,nomepais,nomepaisingles,datainclusao,dataatualizacao) VALUES
(1, 'AFEGANISTÃO', 'AFGHANISTAN', now(),now()),
(2, 'ACROTÍRI E DECELIA', 'AKROTIRI E DEKÉLIA', now(),now()),
(3, 'ÁFRICA DO SUL', 'SOUTH AFRICA', now(),now()),
(4, 'ALBÂNIA', 'ALBANIA', now(),now()),
(5, 'ALEMANHA', 'GERMANY', now(),now()),
(6, 'AMERICAN SAMOA', 'AMERICAN SAMOA', now(),now()),
(7, 'ANDORRA', 'ANDORRA', now(),now()),
(8, 'ANGOLA', 'ANGOLA', now(),now()),
(9, 'ANGUILLA', 'ANGUILLA', now(),now()),
(10, 'ANTÍGUA E BARBUDA', 'ANTIGUA AND BARBUDA', now(),now()),
(11, 'ANTILHAS NEERLANDESAS', 'NETHERLANDS ANTILLES', now(),now()),
(12, 'ARÁBIA SAUDITA', 'SAUDI ARABIA', now(),now()),
(13, 'ARGÉLIA', 'ALGERIA', now(),now()),
(14, 'ARGENTINA', 'ARGENTINA', now(),now()),
(15, 'ARMÉNIA', 'ARMENIA', now(),now()),
(16, 'ARUBA', 'ARUBA', now(),now()),
(17, 'AUSTRÁLIA', 'AUSTRALIA', now(),now()),
(18, 'ÁUSTRIA', 'AUSTRIA', now(),now()),
(19, 'AZERBAIJÃO', 'AZERBAIJAN', now(),now()),
(20, 'BAHAMAS', 'BAHAMAS, THE', now(),now()),
(21, 'BANGLADECHE', 'BANGLADESH', now(),now()),
(22, 'BARBADOS', 'BARBADOS', now(),now()),
(23, 'BARÉM', 'BAHRAIN', now(),now()),
(24, 'BASSAS DA ÍNDIA', 'BASSAS DA INDIA', now(),now()),
(25, 'BÉLGICA', 'BELGIUM', now(),now()),
(26, 'BELIZE', 'BELIZE', now(),now()),
(27, 'BENIM', 'BENIN', now(),now()),
(28, 'BERMUDAS', 'BERMUDA', now(),now()),
(29, 'BIELORRÚSSIA', 'BELARUS', now(),now()),
(30, 'BOLÍVIA', 'BOLIVIA', now(),now()),
(31, 'BÓSNIA E HERZEGOVINA', 'BOSNIA AND HERZEGOVINA', now(),now()),
(32, 'BOTSUANA', 'BOTSWANA', now(),now()),
(33, 'BRASIL', 'BRAZIL', now(),now()),
(34, 'BRUNEI DARUSSALAM', 'BRUNEI DARUSSALAM', now(),now()),
(35, 'BULGÁRIA', 'BULGARIA', now(),now()),
(36, 'BURQUINA FASO', 'BURKINA FASO', now(),now()),
(37, 'BURUNDI', 'BURUNDI', now(),now()),
(38, 'BUTÃO', 'BHUTAN', now(),now()),
(39, 'CABO VERDE', 'CAPE VERDE', now(),now()),
(40, 'CAMARÕES', 'CAMEROON', now(),now()),
(41, 'CAMBOJA', 'CAMBODIA', now(),now()),
(42, 'CANADÁ', 'CANADA', now(),now()),
(43, 'CATAR', 'QATAR', now(),now()),
(44, 'CAZAQUISTÃO', 'KAZAKHSTAN', now(),now()),
(45, 'CENTRO-AFRICANA REPÚBLICA', 'CENTRAL AFRICAN REPUBLIC', now(),now()),
(46, 'CHADE', 'CHAD', now(),now()),
(47, 'CHILE', 'CHILE', now(),now()),
(48, 'CHINA', 'CHINA', now(),now()),
(49, 'CHIPRE', 'CYPRUS', now(),now()),
(50, 'COLÔMBIA', 'COLOMBIA', now(),now()),
(51, 'COMORES', 'COMOROS', now(),now()),
(52, 'CONGO', 'CONGO', now(),now()),
(53, 'CONGO REPÚBLICA DEMOCRÁTICA', 'CONGO DEMOCRATIC REPUBLIC', now(),now()),
(54, 'COREIA DO NORTE', 'KOREA NORTH', now(),now()),
(55, 'COREIA DO SUL', 'KOREA SOUTH', now(),now()),
(56, 'COSTA DO MARFIM', 'IVORY COAST', now(),now()),
(57, 'COSTA RICA', 'COSTA RICA', now(),now()),
(58, 'CROÁCIA', 'CROATIA', now(),now()),
(59, 'CUBA', 'CUBA', now(),now()),
(60, 'DINAMARCA', 'DENMARK', now(),now()),
(61, 'DOMÍNICA', 'DOMINICA', now(),now()),
(62, 'EGIPTO', 'EGYPT', now(),now()),
(63, 'EMIRADOS ÁRABES UNIDOS', 'UNITED ARAB EMIRATES', now(),now()),
(64, 'EQUADOR', 'ECUADOR', now(),now()),
(65, 'ERITREIA', 'ERITREA', now(),now()),
(66, 'ESLOVÁQUIA', 'SLOVAKIA', now(),now()),
(67, 'ESLOVÉNIA', 'SLOVENIA', now(),now()),
(68, 'ESPANHA', 'SPAIN', now(),now()),
(69, 'ESTADOS UNIDOS', 'UNITED STATES', now(),now()),
(70, 'ESTÓNIA', 'ESTONIA', now(),now()),
(71, 'ETIÓPIA', 'ETHIOPIA', now(),now()),
(72, 'FAIXA DE GAZA', 'GAZA STRIP', now(),now()),
(73, 'FIJI', 'FIJI', now(),now()),
(74, 'FILIPINAS', 'PHILIPPINES', now(),now()),
(75, 'FINLÂNDIA', 'FINLAND', now(),now()),
(76, 'FRANÇA', 'FRANCE', now(),now()),
(77, 'GABÃO', 'GABON', now(),now()),
(78, 'GÂMBIA', 'GAMBIA', now(),now()),
(79, 'GANA', 'GHANA', now(),now()),
(80, 'GEÓRGIA', 'GEORGIA', now(),now()),
(81, 'GIBRALTAR', 'GIBRALTAR', now(),now()),
(82, 'GRANADA', 'GRENADA', now(),now()),
(83, 'GRÉCIA', 'GREECE', now(),now()),
(84, 'GRONELÂNDIA', 'GREENLAND', now(),now()),
(85, 'GUADALUPE', 'GUADELOUPE', now(),now()),
(86, 'GUAM', 'GUAM', now(),now()),
(87, 'GUATEMALA', 'GUATEMALA', now(),now()),
(88, 'GUERNSEY', 'GUERNSEY', now(),now()),
(89, 'GUIANA', 'GUYANA', now(),now()),
(90, 'GUIANA FRANCESA', 'FRENCH GUIANA', now(),now()),
(91, 'GUINÉ', 'GUINEA', now(),now()),
(92, 'GUINÉ EQUATORIAL', 'EQUATORIAL GUINEA', now(),now()),
(93, 'GUINÉ-BISSAU', 'GUINEA-BISSAU', now(),now()),
(94, 'HAITI', 'HAITI', now(),now()),
(95, 'HONDURAS', 'HONDURAS', now(),now()),
(96, 'HONG KONG', 'HONG KONG', now(),now()),
(97, 'HUNGRIA', 'HUNGARY', now(),now()),
(98, 'IÉMEN', 'YEMEN', now(),now()),
(99, 'ILHA BOUVET', 'BOUVET ISLAND', now(),now()),
(100, 'ILHA CHRISTMAS', 'CHRISTMAS ISLAND', now(),now()),
(101, 'ILHA DE CLIPPERTON', 'CLIPPERTON ISLAND', now(),now()),
(102, 'ILHA DE JOÃO DA NOVA', 'JUAN DE NOVA ISLAND', now(),now()),
(103, 'ILHA DE MAN', 'ISLE OF MAN', now(),now()),
(104, 'ILHA DE NAVASSA', 'NAVASSA ISLAND', now(),now()),
(105, 'ILHA EUROPA', 'EUROPA ISLAND', now(),now()),
(106, 'ILHA NORFOLK', 'NORFOLK ISLAND', now(),now()),
(107, 'ILHA TROMELIN', 'TROMELIN ISLAND', now(),now()),
(108, 'ILHAS ASHMORE E CARTIER', 'ASHMORE AND CARTIER ISLANDS', now(),now()),
(109, 'ILHAS CAIMAN', 'CAYMAN ISLANDS', now(),now()),
(110, 'ILHAS COCOS (KEELING)', 'COCOS (KEELING) ISLANDS', now(),now()),
(111, 'ILHAS COOK', 'COOK ISLANDS', now(),now()),
(112, 'ILHAS DO MAR DE CORAL', 'CORAL SEA ISLANDS', now(),now()),
(113, 'ILHAS FALKLANDS (ILHAS MALVINAS)', 'FALKLAND ISLANDS (ISLAS MALVINAS)', now(),now()),
(114, 'ILHAS FEROE', 'FAROE ISLANDS', now(),now()),
(115, 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', now(),now()),
(116, 'ILHAS MARIANAS DO NORTE', 'NORTHERN MARIANA ISLANDS', now(),now()),
(117, 'ILHAS MARSHALL', 'MARSHALL ISLANDS', now(),now()),
(118, 'ILHAS PARACEL', 'PARACEL ISLANDS', now(),now()),
(119, 'ILHAS PITCAIRN', 'PITCAIRN ISLANDS', now(),now()),
(120, 'ILHAS SALOMÃO', 'SOLOMON ISLANDS', now(),now()),
(121, 'ILHAS SPRATLY', 'SPRATLY ISLANDS', now(),now()),
(122, 'ILHAS VIRGENS AMERICANAS', 'UNITED STATES VIRGIN ISLANDS', now(),now()),
(123, 'ILHAS VIRGENS BRITÂNICAS', 'BRITISH VIRGIN ISLANDS', now(),now()),
(124, 'ÍNDIA', 'INDIA', now(),now()),
(125, 'INDONÉSIA', 'INDONESIA', now(),now()),
(126, 'IRÃO', 'IRAN', now(),now()),
(127, 'IRAQUE', 'IRAQ', now(),now()),
(128, 'IRLANDA', 'IRELAND', now(),now()),
(129, 'ISLÂNDIA', 'ICELAND', now(),now()),
(130, 'ISRAEL', 'ISRAEL', now(),now()),
(131, 'ITÁLIA', 'ITALY', now(),now()),
(132, 'JAMAICA', 'JAMAICA', now(),now()),
(133, 'JAN MAYEN', 'JAN MAYEN', now(),now()),
(134, 'JAPÃO', 'JAPAN', now(),now()),
(135, 'JERSEY', 'JERSEY', now(),now()),
(136, 'JIBUTI', 'DJIBOUTI', now(),now()),
(137, 'JORDÂNIA', 'JORDAN', now(),now()),
(138, 'KIRIBATI', 'KIRIBATI', now(),now()),
(139, 'KOWEIT', 'KUWAIT', now(),now()),
(140, 'LAOS', 'LAOS', now(),now()),
(141, 'LESOTO', 'LESOTHO', now(),now()),
(142, 'LETÓNIA', 'LATVIA', now(),now()),
(143, 'LÍBANO', 'LEBANON', now(),now()),
(144, 'LIBÉRIA', 'LIBERIA', now(),now()),
(145, 'LÍBIA', 'LIBYAN ARAB JAMAHIRIYA', now(),now()),
(146, 'LISTENSTAINE', 'LIECHTENSTEIN', now(),now()),
(147, 'LITUÂNIA', 'LITHUANIA', now(),now()),
(148, 'LUXEMBURGO', 'LUXEMBOURG', now(),now()),
(149, 'MACAU', 'MACAO', now(),now()),
(150, 'MACEDÓNIA', 'MACEDONIA', now(),now()),
(151, 'MADAGÁSCAR', 'MADAGASCAR', now(),now()),
(152, 'MALÁSIA', 'MALAYSIA', now(),now()),
(153, 'MALAVI', 'MALAWI', now(),now()),
(154, 'MALDIVAS', 'MALDIVES', now(),now()),
(155, 'MALI', 'MALI', now(),now()),
(156, 'MALTA', 'MALTA', now(),now()),
(157, 'MARROCOS', 'MOROCCO', now(),now()),
(158, 'MARTINICA', 'MARTINIQUE', now(),now()),
(159, 'MAURÍCIA', 'MAURITIUS', now(),now()),
(160, 'MAURITÂNIA', 'MAURITANIA', now(),now()),
(161, 'MAYOTTE', 'MAYOTTE', now(),now()),
(162, 'MÉXICO', 'MEXICO', now(),now()),
(163, 'MIANMAR', 'MYANMAR BURMA', now(),now()),
(164, 'MICRONÉSIA', 'MICRONESIA', now(),now()),
(165, 'MOÇAMBIQUE', 'MOZAMBIQUE', now(),now()),
(166, 'MOLDÁVIA', 'MOLDOVA', now(),now()),
(167, 'MÓNACO', 'MONACO', now(),now()),
(168, 'MONGÓLIA', 'MONGOLIA', now(),now()),
(169, 'MONTENEGRO', 'MONTENEGRO', now(),now()),
(170, 'MONTSERRAT', 'MONTSERRAT', now(),now()),
(171, 'NAMÍBIA', 'NAMIBIA', now(),now()),
(172, 'NAURU', 'NAURU', now(),now()),
(173, 'NEPAL', 'NEPAL', now(),now()),
(174, 'NICARÁGUA', 'NICARAGUA', now(),now()),
(175, 'NÍGER', 'NIGER', now(),now()),
(176, 'NIGÉRIA', 'NIGERIA', now(),now()),
(177, 'NIUE', 'NIUE', now(),now()),
(178, 'NORUEGA', 'NORWAY', now(),now()),
(179, 'NOVA CALEDÓNIA', 'NEW CALEDONIA', now(),now()),
(180, 'NOVA ZELÂNDIA', 'NEW ZEALAND', now(),now()),
(181, 'OMÃ', 'OMAN', now(),now()),
(182, 'PAÍSES BAIXOS', 'NETHERLANDS', now(),now()),
(183, 'PALAU', 'PALAU', now(),now()),
(184, 'PALESTINA', 'PALESTINE', now(),now()),
(185, 'PANAMÁ', 'PANAMA', now(),now()),
(186, 'PAPUÁSIA-NOVA GUINÉ', 'PAPUA NEW GUINEA', now(),now()),
(187, 'PAQUISTÃO', 'PAKISTAN', now(),now()),
(188, 'PARAGUAI', 'PARAGUAY', now(),now()),
(189, 'PERU', 'PERU', now(),now()),
(190, 'POLINÉSIA FRANCESA', 'FRENCH POLYNESIA', now(),now()),
(191, 'POLÓNIA', 'POLAND', now(),now()),
(192, 'PORTO RICO', 'PUERTO RICO', now(),now()),
(193, 'PORTUGAL', 'PORTUGAL', now(),now()),
(194, 'QUÉNIA', 'KENYA', now(),now()),
(195, 'QUIRGUIZISTÃO', 'KYRGYZSTAN', now(),now()),
(196, 'REINO UNIDO', 'UNITED KINGDOM', now(),now()),
(197, 'REPÚBLICA CHECA', 'CZECH REPUBLIC', now(),now()),
(198, 'REPÚBLICA DOMINICANA', 'DOMINICAN REPUBLIC', now(),now()),
(199, 'ROMÉNIA', 'ROMANIA', now(),now()),
(200, 'RUANDA', 'RWANDA', now(),now()),
(201, 'RÚSSIA', 'RUSSIAN FEDERATION', now(),now()),
(202, 'SAHARA OCCIDENTAL', 'WESTERN SAHARA', now(),now()),
(203, 'SALVADOR', 'EL SALVADOR', now(),now()),
(204, 'SAMOA', 'SAMOA', now(),now()),
(205, 'SANTA HELENA', 'SAINT HELENA', now(),now()),
(206, 'SANTA LÚCIA', 'SAINT LUCIA', now(),now()),
(207, 'SANTA SÉ', 'HOLY SEE', now(),now()),
(208, 'SÃO CRISTÓVÃO E NEVES', 'SAINT KITTS AND NEVIS', now(),now()),
(209, 'SÃO MARINO', 'SAN MARINO', now(),now()),
(210, 'SÃO PEDRO E MIQUELÃO', 'SAINT PIERRE AND MIQUELON', now(),now()),
(211, 'SÃO TOMÉ E PRÍNCIPE', 'SAO TOME AND PRINCIPE', now(),now()),
(212, 'SÃO VICENTE E GRANADINAS', 'SAINT VINCENT AND THE GRENADINES', now(),now()),
(213, 'SEICHELES', 'SEYCHELLES', now(),now()),
(214, 'SENEGAL', 'SENEGAL', now(),now()),
(215, 'SERRA LEOA', 'SIERRA LEONE', now(),now()),
(216, 'SÉRVIA', 'SERBIA', now(),now()),
(217, 'SINGAPURA', 'SINGAPORE', now(),now()),
(218, 'SÍRIA', 'SYRIA', now(),now()),
(219, 'SOMÁLIA', 'SOMALIA', now(),now()),
(220, 'SRI LANCA', 'SRI LANKA', now(),now()),
(221, 'SUAZILÂNDIA', 'SWAZILAND', now(),now()),
(222, 'SUDÃO', 'SUDAN', now(),now()),
(223, 'SUÉCIA', 'SWEDEN', now(),now()),
(224, 'SUÍÇA', 'SWITZERLAND', now(),now()),
(225, 'SURINAME', 'SURINAME', now(),now()),
(226, 'SVALBARD', 'SVALBARD', now(),now()),
(227, 'TAILÂNDIA', 'THAILAND', now(),now()),
(228, 'TAIWAN', 'TAIWAN', now(),now()),
(229, 'TAJIQUISTÃO', 'TAJIKISTAN', now(),now()),
(230, 'TANZÂNIA', 'TANZANIA', now(),now()),
(231, 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO', 'BRITISH INDIAN OCEAN TERRITORY', now(),now()),
(232, 'TERRITÓRIO DAS ILHAS HEARD E MCDONALD', 'HEARD ISLAND AND MCDONALD ISLANDS', now(),now()),
(233, 'TIMOR-LESTE', 'TIMOR-LESTE', now(),now()),
(234, 'TOGO', 'TOGO', now(),now()),
(235, 'TOKELAU', 'TOKELAU', now(),now()),
(236, 'TONGA', 'TONGA', now(),now()),
(237, 'TRINDADE E TOBAGO', 'TRINIDAD AND TOBAGO', now(),now()),
(238, 'TUNÍSIA', 'TUNISIA', now(),now()),
(239, 'TURKS E CAICOS', 'TURKS AND CAICOS ISLANDS', now(),now()),
(240, 'TURQUEMENISTÃO', 'TURKMENISTAN', now(),now()),
(241, 'TURQUIA', 'TURKEY', now(),now()),
(242, 'TUVALU', 'TUVALU', now(),now()),
(243, 'UCRÂNIA', 'UKRAINE', now(),now()),
(244, 'UGANDA', 'UGANDA', now(),now()),
(245, 'URUGUAI', 'URUGUAY', now(),now()),
(246, 'USBEQUISTÃO', 'UZBEKISTAN', now(),now()),
(247, 'VANUATU', 'VANUATU', now(),now()),
(248, 'VENEZUELA', 'VENEZUELA', now(),now()),
(249, 'VIETNAME', 'VIETNAM', now(),now()),
(250, 'WALLIS E FUTUNA', 'WALLIS AND FUTUNA', now(),now()),
(251, 'ZÂMBIA', 'ZAMBIA', now(),now()),
(252, 'ZIMBABUÉ', 'ZIMBABWE',now(),now());